notifications:
  email: false
addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
matrix:
  include:
    - os: osx
      language: generic
      # see https://www.python.org/downloads/mac-osx/ for valid versions
      env:
        - MAC_PYTHON_VERSION=3.6.8
        - MAC_PYTHON_OSX_VERSION=10.6
      sudo: required
install:
  - source ./.travis/osx_setup_python.sh $MAC_PYTHON_VERSION $MAC_PYTHON_OSX_VERSION
  - python --version
  - pip install PyQt5 pure-python-adb
  - pip freeze
script:
  # append "App" to avoid naming conflicts with python library
  - bash ./.travis/osx_build_app.sh main $TRAVIS_TAG
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "DaniilSmirnov"
  - git config --local user.email "littlebigcrafting@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "dist_app/*.dmg"
    - "dist_app/*.pkg"
  skip_cleanup: true
